version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project-k-db
      - POSTGRES_USER=projectKUser
      - POSTGRES_PASSWORD=STr0ngP@ass0rd
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  postgres_data:
