services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: project_k_db
      POSTGRES_USER: project_k_user
      POSTGRES_PASSWORD: project_k_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_k_user -d project_k_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project_k.wsgi:application --workers=4 --bind=0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: "your-secret-key"
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: "postgres://project_k_user:project_k_password@db:5432/project_k_db"
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # Static files (optional, adjust if required)
    # - ./staticfiles:/app/staticfiles:ro

volumes:
  postgres_data:
