version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project_k_db
      - POSTGRES_USER=project_k_user
      - POSTGRES_PASSWORD=project_k_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:

