services:
  - type: web
    name: django-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py makemigrations && sleep 5 && python manage.py migrate && sleep 5 && gunicorn --timeout 600 --bind 0.0.0.0:8000 project_k.wsgi:application



    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DJANGO_DEBUG
        value: "0"
      - key: DATABASE_URL
        value: postgres://project_k_user:project_k_password@your-db-host:5432/project_k_db

