services:
  - type: web
    name: project-k
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project_k.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: project-k-db
          property: connectionString

databases:
  - name: project-k-db
    databaseName: project_k_db
    user: project_k_user
