# Generated by Django 4.2.3 on 2024-12-09 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 9, 5, 56, 15, 409258, tzinfo=datetime.timezone.utc), verbose_name='End Date'),
        ),
    ]
