# Generated by Django 4.2.3 on 2024-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0002_alter_courseschedule_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days_of_week',
            field=models.CharField(help_text='Comma-separated list of weekday numbers (0-6)', max_length=20, verbose_name='Days of Week'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
    ]
