# Generated by Django 4.2.3 on 2024-12-05 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0014_use_autofields_for_pk'),
        ('course_management', '0004_alter_booking_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['date', 'time_slot__start_time'], 'verbose_name': 'Course Schedule', 'verbose_name_plural': 'Course Schedules'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AddField(
            model_name='course',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.calendar'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.event'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='course_management.course'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
