# Generated by Django 4.2.3 on 2024-12-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_alter_courseapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course_management.room'),
        ),
    ]
