# Generated by Django 4.2.3 on 2024-12-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfile',
            options={'verbose_name': 'Client File', 'verbose_name_plural': 'Client Files'},
        ),
    ]
