# Generated by Django 4.2.3 on 2024-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0004_clientfile_uploaded_by_alter_clientfile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('BUSINESS', 'Business')], default='PRIVATE', max_length=10),
        ),
    ]
